
## Build and run: 
## Set env: $(boot2docker shellinit)
# $(boot2docker shellinit) 
# docker build -t rachidbm/lightbikes-client . && docker run rachidbm/lightbikes-client
# $(boot2docker shellinit) && docker run rachidbm/lightbikes-client

FROM node:0.10-onbuild
EXPOSE 3000